### ISSUE TITLE
python S3 upload_file method 

### ISSUE THREAD

**Issue by katiewest820** [aws-observability/aws-otel-lambda#10]
**Is your feature request related to a problem? Please describe.**

X-Ray spans generated by S3 `upload_file` method requests do not have the same trace id as their parent and sibling spans and the parent_id is set to null which causes broken traces.

**Describe the solution you'd like**

To be able to use `upload_file` within our code and not have broken traces. 

**Describe alternatives you've considered**

I had to move away from using `upload_file` and switch to `put_object` which works but if some methods are not instrumented you should call that out in the X-Ray/S3 documentation. 

**Additional context**

**Comment by wangzlei** [comment]
Hi, 
Thanks for providing feedback. The is an opentelemetry python sdk issue not only happens in Lambda. 
Not like `put_object`, boto3 S3 `upload_file` uses multiple threads to upload to S3 bucket, Openelemetry boto3 instrumentation cannot handle this special case and cause the span cannot find its parent span(here parent is the Lambda handler function span). Any boto3 S3 function using [S3 transfer manager](https://github.com/boto/s3transfer/blob/develop/s3transfer/manager.py) has the same issue, like`download_file`. 
`put_object` can be a workaround because it is not using S3 transfer manager. I will create an issue in OpenTelemetry Python SDK to fix this bug.

**Comment by wangzlei** [comment]
cut an issue in opentelemetry: https://github.com/open-telemetry/opentelemetry-python-contrib/issues/298
