### ISSUE TITLE
README.md incorrect link for collector

### ISSUE THREAD

**Issue by taylorsmithgg** [aws-observability/aws-otel-lambda#126]
> Collector layer aws-otel-collector-ver-0-29-1 contains ADOT Collector for Lambda v0.11.0

links to dotnet layer, not collector

https://aws-otel.github.io/docs/getting-started/lambda/lambda-dotnet

**Comment by NathanielRN** [comment]
Hi @taylorsmithgg , thanks for raising this issue!

Actually, this links to the "Getting Started - Lambda Support for .NET" docs intentionally because .NET is an example of a language that has no layer which can't automatically instrument the OTel SDK like some other layers do 😕 So as a "Collector Layer", it _only_ provides the ADOT Collector which can be used by .NET Lambdas in the absence of a .NET Lambda Layer. (.NET Lambdas just need to manually instrument with the OTel-dotnet SDK).

That's why those "Lambda for .NET" docs say this:

> The ADOT Lambda layer provides a reduced version of the AWS Distro for OpenTelemetry Collector, which can further export OpenTelemetry spans to back-end servers.

> This layer includes a reduced version of the AWS Distro for OpenTelemetry Collector (ADOT Collector), which runs as a Lambda extension.

I think calling it "Collector layer" was done to avoid any confusion that would come about if it were called ".NET layer" but doesn't actually initialize .NET like I mentioned above.

Hopefully that clears it up 🙂

**Comment by vasireddy99** [comment]
Closing this issue and please feel free to re-open for any concerns. Thank you 😄
