### ISSUE TITLE
Unable to send traces to OTEL collector using aws-otel-nodejs-ver-1-0-0 layer

### ISSUE THREAD

**Issue by stephenhong** [aws-observability/aws-otel-lambda#176]
Hello team, I set up a lambda function with Node.js by following this documentation (https://aws-otel.github.io/docs/getting-started/lambda/lambda-js). I have logging exporter (loglevel: debug) and otlp exporter (endpoint to a different OTEL collector hosted on an EC2) enabled in the config.yaml file. However, I'm not seeing the traces going to the OTEL collector. I'm not seeing the logging exporter print the traces in the execution results. I was able to make this work with a lambda function with Python (https://aws-otel.github.io/docs/getting-started/lambda/lambda-python) but it's not working with Node.js which makes me think that there might be an issue with the Node.js layer? Can someone please help me with this issue?

**Comment by NathanielRN** [comment]
Hey Stephen! Thanks for raising this issue.

Hmm, the current `nodejs` layer _should_ be working because we have daily tests that check that the Layer can send traces to the Collector, and that the Collector can send traces to the AWS X-Ray service, so that finally we can pull that Trace and validate its contents across every AWS region where the layers are published. For example, you can see the [retrieved trace map for this test that uses the nodejs-1-0-0 layer](https://github.com/aws-observability/aws-otel-lambda/runs/4266697193?check_suite_focus=true#step:21:52).

However, the tests use an OTel Collector running locally within the same layer. Actually, all the layers (besides the collector layer do this). Connecting the OTel NodeJS SDK (inside the layer) to an OTel Collector has been notoriously difficult at times 🙂. Can you describe how/why you send to a different collector from [the ADOT Collector](https://github.com/aws-observability/aws-otel-collector) package within the layer? The ADOT Collector is just a subset of the OTel Collector Contrib. That would probably involve setting the `OTEL_EXPORTER_OTLP_ENDPOINT` environment variable and providing necessary permissions for the layer to access that EC2 instance.

Please let me know if this makes sense! 🙂

**Comment by stephenhong** [comment]
Hello Nathaniel, it is working now. I just needed to add http parameter under otlp receiver in my config.yaml file. Thank you.
