### ISSUE TITLE
Java Agent Lambda Layer first invocation has no instrumentation traces; works on subsequent traces

### ISSUE THREAD

**Issue by NathanielRN** [aws-observability/aws-otel-lambda#200]
# Description

I was using the `aws-otel-java-agent-ver-1-7-0` Lambda layer on a Java 11 Lambda and noticed that while the first invocation does not have an S3 AWS SDK trace for the Sample App on the OTel Lambda repo, subsequent invocations _do_ have it.

First invocation with the `Initialization` Lambda trace but no `S3` trace:

<img width="1303" alt="image" src="https://user-images.githubusercontent.com/23139455/146600466-14014ab9-1a9b-42a7-9b86-9242ed00a5d9.png">

Subsequent invocation which still has the `Initialization` Lambda trace but now does have the `S3` trace:

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/23139455/146600589-3eb96a69-b046-4217-8663-60119571b350.png">

cc @anuraaga

**Comment by anuraaga** [comment]
This is usually because in the beginning the app takes so long to initialize java code that the export has a reasonable chance of timing out, even with a 10s timeout. Java agent 1.9+ changes the export pipeline logic significantly which should have faster cold start time, it will be good to verify whether similar issues still happen with 1.9

**Comment by NathanielRN** [comment]
Thanks for the explanation, sounds great! I see we're still using OTel Java 1.7 on the current Layer:

https://github.com/aws-observability/aws-otel-lambda/blob/ffcff3f7c2f6d9b53963f06ebcf5c4c9902cb20e/java/build.gradle.kts#L27-L28

So I'll close this issue for now since we know it is a limitation. Will look forward to our update to OTel Java 1.9!
