### ISSUE TITLE
Python Lambda instrumentation fails with error :Unable to import module 'aws_observability': cannot import name 'AwsXRayIdsGenerator'

### ISSUE THREAD

**Issue by CeeBeeCee** [aws-observability/aws-otel-lambda#21]
I build and deployed the Python sample app and layer and when I executed the function, I got this error :

 Unable to import module 'aws_observability': cannot import name 'AwsXRayIdsGenerator'

I followed every step documented in https://github.com/aws-observability/aws-otel-lambda/tree/main/sample-apps/python-lambda

Attached is the full log.
[log-events-viewer-result.txt](https://github.com/aws-observability/aws-otel-lambda/files/6314117/log-events-viewer-result.txt)

**Comment by CeeBeeCee** [comment]
I'm running Python 3.8 by the way

**Comment by mat-rumian** [comment]
@CeeBeeCee I've faced this issue too. The problem is present because `aws_observability` dependencies are set to latest. It happened because OpenTelemetry Python community release new version where `AwsXRayIdsGenerator` was changed to `AwsXRayIdGenerator`. If you fix that you are going to face much more issues related to name changes in the OT Python main stream.

**Comment by CeeBeeCee** [comment]
@mat-rumian : Ah, I see that now. Thanks! I'll wait for the AWS folks to refactor their sample code and their instrumentation script.

class AwsXRayIdGenerator(IdGenerator):
    """Generates tracing IDs compatible with the AWS X-Ray tracing service. In
    the X-Ray system, the first 32 bits of the `TraceId` are the Unix epoch time
    in seconds. Since spans (AWS calls them segments) with an embedded timestamp
    more than 30 days ago are rejected, a purely random `TraceId` risks being
    rejected by the service.
