### ISSUE TITLE
AWS Lambda Layer Collector (aoc_extension) is missing processors.

### ISSUE THREAD

**Issue by mat-rumian** [aws-observability/aws-otel-lambda#22]
According to [AWS OTel Collector capabilities](https://github.com/aws-observability/aws-otel-collector#aws-otel-collector-built-in-components-in-2020) the OpenTelemetry Lambda Layer Collector (the one from extensions) should have similar functionality. In example to obtain `cloud.*` tags, additional collector has to be set up to get it by `resourcedetectionprocessor`.

**Comment by wangzlei** [comment]
[OTel Lambda design](https://github.com/open-telemetry/opentelemetry-lambda/blame/a1bda237c9d4a23e4bb2d2e342ce231d299ac0d6/docs/design_proposal.md#L23) intends to remove all of processors from Collector, to make sure the receiver and exporter are in same thread. We don't need EKS/ECS/Beanstalk attributes in Lambda environment so haven't thought about using resourcedetectionprocessor in Lambda. Instead of that we'd implement LambdaResourceDetector in SDK side,.

**Comment by mat-rumian** [comment]
Got it :) Thanks for clarification @wangzlei
