### ISSUE TITLE
Security configuration/recommendation for OpenTelemetry vendor keys

### ISSUE THREAD

**Issue by ericksoen** [aws-observability/aws-otel-lambda#225]
**Is your feature request related to a problem? Please describe.**
One of the default behaviors for OpenTelemetry collectors is to handle variable expansion. For hosting patterns like an ECS task, this means that we can retrieve and decrypt vendor keys from services like SSM Parameter store and inject them as environment variables. 

With AWS Lambda, the collector extension starts _before_ any application code executes. This means that strategies to [configure encryption in transit](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html#configuration-envvars-encryption) are not viable since it requires application code (3e) to decrypt the environment variables. We're looking for security recommendations to minimize exposure of sensitive vendor keys in plain-text as environment variables, which appears to be the only viable alternative at this point (correct me if I'm missing something obvious)
 
**Describe the solution you'd like**
1. Built-in configuration option to retrieve and set environment variables for OpenTelemetry Collector from AWS services like SSM parameter store

**Describe alternatives you've considered**

1. Build and manage custom Lambda layer to either retrieve secrets from SSM or decrypt environment variables

~~Note: I have not yet performed technical evaluation to understand the execution sequence between `AWS_LAMBDA_EXEC_WRAPPER` and [Lambda extension setup](https://docs.aws.amazon.com/lambda/latest/dg/using-extensions.html#using-extensions-env)~~

> Lambda looks for extensions in the `opt/extensions` directory, interprets each file as an executable bootstrap for launching the extension, and starts all extensions in parallel

Updated note: after some additional validation, the executables in `/opt/extensions` execute prior to the script registered via `AWS_LAMBDA_EXEC_WRAPPER`. This means that we cannot rely on any functionality in the `AWS_LAMBDA_EXEC_WRAPPER` to pre-fetch and set environment variables.

**Additional context**
1. May overlap with [OpenTelemetry Collector: External Configuration Sources](https://docs.google.com/document/d/1jUfWCUgvXaWelZ81Ot2yprFWHyjdjMxvm75IdhCyaY8/edit#heading=h.d3c2e1ihztjw)

**Comment by Aneurysm9** [comment]
There have been a number of proposals since the external configuration source document listed, including [this one for CLI/URL-based configuration](https://docs.google.com/document/d/1XlDpS8-a4Ds6uoe6C6WgO8mCpDaQNufcHSEmBpiCdI0/edit) and [this one for file-based meta-configuration](https://github.com/open-telemetry/opentelemetry-collector/issues/4190).  I'm presently starting to write another proposal that attempts to bridge some of the gaps between those and [this draft PR](https://github.com/open-telemetry/opentelemetry-collector/pull/4742) that I'm not sure exposes enough meta-configuration.

For this particular use case I would think that a [`ConfigProvider`](https://pkg.go.dev/go.opentelemetry.io/collector@v0.45.0/service#ConfigProvider) implementation that can read from SSM parameter store or Secrets Manager combined with the ability to template a base configuration with replacements from sources other than the environment `ConfigProvider` would be ideal.

**Comment by ericksoen** [comment]
Thanks! I'll take a look at those proposals as well as the linked ConfigProvider. I updated the alternatives described above to remove the option to use a custom `AWS_LAMBDA_EXEC_WRAPPER` to fetch and set environment variables as it does not execute _before_ extension initialization.
