### ISSUE TITLE
Traces broken when using third party exporter with Lambda

### ISSUE THREAD

**Issue by katiewest820** [aws-observability/aws-otel-lambda#9]
**Is your feature request related to a problem? Please describe.**

When using the AWS Otel Collector with a third party exporter (NewRelic) only spans that are related to transactions within the lambda are exported. All other spans that are a part of the trace are not available for export. For example: A request that is started in API Gateway that invokes a Lambda; we are only able to export the spans related to the lambda and don't have the ability to configure an exporter for the spans related to API Gateway. This results in broken and incomplete traces. 

**Describe the solution you'd like**

It is critical that we can export a complete trace in order to use this feature effectively. 

**Describe alternatives you've considered**

We need to be able to configure third party exporters for all services that can invoke lambdas. This could either be individually or more likely from something like X-Ray. 

**Additional context**

**Comment by wangzlei** [comment]
Hi,

The collector inlined in OTel Lambda Python layer is based on [aws-otel-collector](https://github.com/aws-observability/aws-otel-collector#aws-otel-collector-built-in-components-in-2020), so, not all of exporters are supported. Except the strategy reason, we don't involve all of Collector components because we have to control the size of Lambda dependencies due to [Lambda limits](https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html).

As a workaround, you can build your custom layer, involve the third party exporter you need based on your config. Please see code:
https://github.com/aws-observability/aws-otel-lambda/blob/main/extensions/aoc-extension/cmd/aoc-lambda-extension/main.go#L24
and
https://github.com/aws-observability/aws-otel-collector/blob/main/pkg/lambdacomponents/defaults.go

**Comment by katiewest820** [comment]
Hey @wangzlei,

Sorry I don't think I explained very well what has been done so far. Yes I have been able to successfully create a custom layer pulling in the New Relic exporter, involving the code you linked. 

With these modifications I am able to get the spans generated by actions performed within the function invocation. But what is missing is the upstream span data. In order for this feature to be useful I need to be able to export a complete trace to the third party exporter. This appears to not be possible at the moment?

Is there a way or a future plan to allow users to configure the aws-otel-collector and third party exporter from other AWS services? 
My example is API Gateway; I can only export to X-Ray or CloudWatch but in order to collect a complete trace I need to have a way to export those spans to New Relic from somewhere in AWS.

**Comment by wangzlei** [comment]
Do you mean the spans of API gateway and Lambda service? Those spans are not generated and sent by AWS Lambda container, they will be sent to xray directly.

**Comment by EddieEldridge** [comment]
> The collector inlined in OTel Lambda Python layer is based on [aws-otel-collector](https://github.com/aws-observability/aws-otel-collector#aws-otel-collector-built-in-components-in-2020)

Is this still the case? i.e If I want to find a list of all the available components for the packaged Collector, I should look [here](https://aws-observability.github.io/aws-otel-collector/) ?
